# Generated by Django 5.0.6 on 2024-06-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_excelfile_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='img',
            field=models.FileField(max_length=128, upload_to='cityLogo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='filePath',
            field=models.FileField(max_length=128, upload_to='excel', verbose_name='Excel文件'),
        ),
    ]
