# Generated by Django 5.0.6 on 2024-06-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_city_img_alter_excelfile_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.CharField(max_length=64, verbose_name='收/支'),
        ),
    ]
